spring:
  data:
    mongodb:
      uri: mongodb+srv://test:test22@cluster0.zov8g.mongodb.net/dashboard?retryWrites=true&w=majority
      port: 8080
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: edecb44d7953345f4f52
            client-secret: b1f1638e75f7752b09216eed139253a6963f8bc0